//*
// Copyright 2025 Saber authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: databus.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DatabusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabusRequest) Reset() {
	*x = DatabusRequest{}
	mi := &file_databus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabusRequest) ProtoMessage() {}

func (x *DatabusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_databus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabusRequest.ProtoReflect.Descriptor instead.
func (*DatabusRequest) Descriptor() ([]byte, []int) {
	return file_databus_proto_rawDescGZIP(), []int{0}
}

func (x *DatabusRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *DatabusRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *DatabusRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type DatabusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Errmsg        string                 `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabusResponse) Reset() {
	*x = DatabusResponse{}
	mi := &file_databus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabusResponse) ProtoMessage() {}

func (x *DatabusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_databus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabusResponse.ProtoReflect.Descriptor instead.
func (*DatabusResponse) Descriptor() ([]byte, []int) {
	return file_databus_proto_rawDescGZIP(), []int{1}
}

func (x *DatabusResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DatabusResponse) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

var File_databus_proto protoreflect.FileDescriptor

const file_databus_proto_rawDesc = "" +
	"\n" +
	"\rdatabus.proto\"\xba\x01\n" +
	"\x0eDatabusRequest\x12\x1a\n" +
	"\bclientID\x18\x01 \x01(\tR\bclientID\x126\n" +
	"\aheaders\x18\x02 \x03(\v2\x1c.DatabusRequest.HeadersEntryR\aheaders\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\x0fDatabusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x16\n" +
	"\x06errmsg\x18\x02 \x01(\tR\x06errmsg2C\n" +
	"\x0eDatabusService\x121\n" +
	"\bPushData\x12\x0f.DatabusRequest\x1a\x10.DatabusResponse\"\x00(\x01B\tZ\a.;protob\x06proto3"

var (
	file_databus_proto_rawDescOnce sync.Once
	file_databus_proto_rawDescData []byte
)

func file_databus_proto_rawDescGZIP() []byte {
	file_databus_proto_rawDescOnce.Do(func() {
		file_databus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_databus_proto_rawDesc), len(file_databus_proto_rawDesc)))
	})
	return file_databus_proto_rawDescData
}

var file_databus_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_databus_proto_goTypes = []any{
	(*DatabusRequest)(nil),  // 0: DatabusRequest
	(*DatabusResponse)(nil), // 1: DatabusResponse
	nil,                     // 2: DatabusRequest.HeadersEntry
}
var file_databus_proto_depIdxs = []int32{
	2, // 0: DatabusRequest.headers:type_name -> DatabusRequest.HeadersEntry
	0, // 1: DatabusService.PushData:input_type -> DatabusRequest
	1, // 2: DatabusService.PushData:output_type -> DatabusResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_databus_proto_init() }
func file_databus_proto_init() {
	if File_databus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_databus_proto_rawDesc), len(file_databus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_databus_proto_goTypes,
		DependencyIndexes: file_databus_proto_depIdxs,
		MessageInfos:      file_databus_proto_msgTypes,
	}.Build()
	File_databus_proto = out.File
	file_databus_proto_goTypes = nil
	file_databus_proto_depIdxs = nil
}
