//*
// Copyright 2025 Saber authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: databus.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DatabusService_PushData_FullMethodName = "/DatabusService/PushData"
)

// DatabusServiceClient is the client API for DatabusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatabusServiceClient interface {
	PushData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DatabusRequest, DatabusResponse], error)
}

type databusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatabusServiceClient(cc grpc.ClientConnInterface) DatabusServiceClient {
	return &databusServiceClient{cc}
}

func (c *databusServiceClient) PushData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DatabusRequest, DatabusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DatabusService_ServiceDesc.Streams[0], DatabusService_PushData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DatabusRequest, DatabusResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatabusService_PushDataClient = grpc.ClientStreamingClient[DatabusRequest, DatabusResponse]

// DatabusServiceServer is the server API for DatabusService service.
// All implementations must embed UnimplementedDatabusServiceServer
// for forward compatibility.
type DatabusServiceServer interface {
	PushData(grpc.ClientStreamingServer[DatabusRequest, DatabusResponse]) error
	mustEmbedUnimplementedDatabusServiceServer()
}

// UnimplementedDatabusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatabusServiceServer struct{}

func (UnimplementedDatabusServiceServer) PushData(grpc.ClientStreamingServer[DatabusRequest, DatabusResponse]) error {
	return status.Error(codes.Unimplemented, "method PushData not implemented")
}
func (UnimplementedDatabusServiceServer) mustEmbedUnimplementedDatabusServiceServer() {}
func (UnimplementedDatabusServiceServer) testEmbeddedByValue()                        {}

// UnsafeDatabusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatabusServiceServer will
// result in compilation errors.
type UnsafeDatabusServiceServer interface {
	mustEmbedUnimplementedDatabusServiceServer()
}

func RegisterDatabusServiceServer(s grpc.ServiceRegistrar, srv DatabusServiceServer) {
	// If the following call panics, it indicates UnimplementedDatabusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatabusService_ServiceDesc, srv)
}

func _DatabusService_PushData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DatabusServiceServer).PushData(&grpc.GenericServerStream[DatabusRequest, DatabusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatabusService_PushDataServer = grpc.ClientStreamingServer[DatabusRequest, DatabusResponse]

// DatabusService_ServiceDesc is the grpc.ServiceDesc for DatabusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatabusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DatabusService",
	HandlerType: (*DatabusServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushData",
			Handler:       _DatabusService_PushData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "databus.proto",
}
